package pantalla;

import java.awt.event.ActionListener;
import logica.ManejoArchivos;

/**
 *
 * @author harol
 */
public class Pantalla extends javax.swing.JFrame {
    
    /*Borde para mover la pestaña, creamos dos variables para cada eje, x, y
    */
    int xMouse, yMouse;
    
    public Pantalla() {
        initComponents();
}       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 27, 29));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(197, 211, 255));
        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 211, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contactos");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 179, 219));
        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(161, 179, 219));
        jLabel2.setText("Número");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 123, -1, -1));

        jButton1.setBackground(new java.awt.Color(63, 70, 89));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(218, 222, 247));
        jButton1.setText("Ver contactos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 225, -1, -1));

        jButton2.setBackground(new java.awt.Color(176, 198, 255));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(5, 36, 91));
        jButton2.setText("+ Crear nuevo contacto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 163, -1, -1));

        jButton3.setBackground(new java.awt.Color(38, 41, 48));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(218, 222, 247));
        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 226, -1, -1));

        jButton4.setBackground(new java.awt.Color(38, 41, 48));
        jButton4.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(218, 222, 247));
        jButton4.setText("- Eliminar contacto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 226, -1, -1));

        jTextField1.setBackground(new java.awt.Color(42, 45, 54));
        jTextField1.setForeground(new java.awt.Color(193, 209, 245));
        jTextField1.setText("Ingrese el número");
        jTextField1.setBorder(null);
        jTextField1.setCaretColor(new java.awt.Color(175, 186, 214));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField1MousePressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 123, 268, 20));

        jTextField2.setBackground(new java.awt.Color(42, 45, 54));
        jTextField2.setForeground(new java.awt.Color(193, 209, 245));
        jTextField2.setText("Ingrese el nombre");
        jTextField2.setToolTipText("");
        jTextField2.setBorder(null);

        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextField2MousePressed(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 73, 268, 20));

        jButton6.setBackground(new java.awt.Color(201, 204, 213));
        jButton6.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jButton6.setForeground(new java.awt.Color(27, 27, 29));
        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 267, -1, -1));

        jButton7.setBackground(new java.awt.Color(176, 198, 255));
        jButton7.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jButton7.setText("Salir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 267, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(218, 222, 247));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 333, 424, 163));

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(161, 179, 219));
        jLabel4.setText("Nombre - Número");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 299, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/person_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        jLabel5.setMaximumSize(new java.awt.Dimension(254, 254));
        jLabel5.setMinimumSize(new java.awt.Dimension(254, 254));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 30, 40));

        jPanel2.setBackground(new java.awt.Color(27, 27, 29));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /*Botón de VER CONTACTOS
    */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        String contenido = ManejoArchivos.leerArchivo();
        jTextArea1.setText(contenido);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /*Botón de CREAR NUEVOS CONTACTOS
    */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
    // Obtener valores de los cajones
    String nombre = jTextField2.getText();
    String numero = jTextField1.getText();

    // Verificar que ambos cajones no estén vacíos
    if (!nombre.isEmpty() && !numero.isEmpty()) {
        // Unir nombre y número
        String contacto = nombre + "!" + numero;

    // Método para escribir el contacto en el archivo
        ManejoArchivos.escribirContacto(contacto);

    // Limpiar los campos después de agregar el contacto
        jTextField2.setText("");
        jTextField1.setText("");
    } else {
        System.out.println("Ingrese tanto el nombre como el número antes de agregar el contacto.");
    }       
    }//GEN-LAST:event_jButton2ActionPerformed

    /*Botón de ELIMINAR CONTACTO
    */
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    // Obtener valores de cajones
    String nombre = jTextField2.getText();
    String nuevoNumero = jTextField1.getText();

    // Verificar que ambos cajones no estén vacíos
    if (!nombre.isEmpty()) {
        // Método para eliminar el contacto en el archivo
        ManejoArchivos.eliminarContacto(nombre, nuevoNumero);

        // Limpiar los campos después de eliminar el contacto
        jTextField2.setText("");
        jTextField1.setText("");
    } else {
        System.out.println("Ingrese el nombre antes de eliminar el contacto.");
    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /*CAJÓN DE NOMBRE
    */
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed

    }//GEN-LAST:event_jTextField2ActionPerformed

    /*BOTÓN DE LIMPIAR TODO EL ARCHIVO
    */
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    ManejoArchivos.limpiarArchivo();
    // Se impia el JTextArea donde aparece el listado de contactos
    jTextArea1.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    /*BOTÓN DE CERRAR VENTANA
    */
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.dispose();
        
    }//GEN-LAST:event_jButton7ActionPerformed

    /*Botón de ACTUALIZAR CONTACTO
    */
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    // Obtener valores de los cajones    
        String nombre = jTextField2.getText();
        String numero = jTextField1.getText();

    // Verificar que ambos cajones no estén vacíos
    if (!nombre.isEmpty() && !numero.isEmpty()) {
        // Escribir el contacto actualizado en el archivo
        ManejoArchivos.actualizarContacto(nombre, numero);

        // Limpiar los campos después de actualizar
        jTextField2.setText("");
        jTextField1.setText("");
    } else {
        System.out.println("Ingrese tanto el nombre como el número antes de actualizar el contacto.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    /*MOVIMIENTO PARA LA VENTANA CON EL MOUSE
    */
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
//Guardamos la posición del mouse para mover la barra de encima        
    xMouse = evt.getX();
    yMouse = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
//Posición del Mouse en la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
//Configuramos el evento cuando el mouse es arrastrado
        this.setLocation(x - xMouse,y - yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jTextField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MousePressed
//Quitamos el texto al usuario presionar sobre el cajón
        jTextField2.setText("");
    }//GEN-LAST:event_jTextField2MousePressed

    private void jTextField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MousePressed
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}